const parent = document.getElementById("parent");
// console.log(parent);
ReactDOM.createRoot(parent);
const root =ReactDOM.createRoot(parent);
const h2=React.createElement("h2",{},"Welcome to ReactDOM");
root.render(h2);
const li1=React.createElement("li",{},"JavaS");
const li2=React.createElement("li",{},"Python");
const li3=React.createElement("li",{},"NodeJS");
const ul=React.createElement("ul",{} ,[li1,li2,li3]);
root.render(ul);